# Generated by Django 3.2.6 on 2021-08-21 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Librarian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enroll_code', models.IntegerField()),
                ('name', models.CharField(max_length=40)),
                ('address', models.CharField(max_length=40)),
                ('mobile_no', models.BigIntegerField()),
                ('username', models.CharField(max_length=40)),
                ('password', models.IntegerField()),
            ],
        ),
    ]
